---
framework: mocha
preRun:
  command:
    - npm install
    - npm i react
    - npm run compile
preMerge:
  pattern:
    - "./test/socket.io.ts"
postMerge:
  pattern: 
    - "./test/*.ts"
postRun:
  command:
    - node --version
version: 1.1
configFile: mocha.opts
