---
framework: mocha
postMerge:
  pattern:
    - "test/socket.io.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "test/socket.io.ts"
preRun:
  - npm ci
  - npm run compile
postRun:
  - node --version
version: 2.0
